"""Add role to User

Revision ID: 92bbaa7453eb
Revises: 3a8f56e2c34c
Create Date: 2025-08-25 19:59:11.874162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92bbaa7453eb"
down_revision: Union[str, Sequence[str], None] = "3a8f56e2c34c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_films_id"), "films", ["id"], unique=False)
    op.add_column("users", sa.Column("role", sa.String(), nullable=False))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.drop_column("users", "role")
    op.drop_index(op.f("ix_films_id"), table_name="films")
    # ### end Alembic commands ###
